- name: Creates root directory
  file: path="{{root_dir}}/{{domain}}" state=directory mode=0755 owner=root

- name: Add apache vhosts configuration.
  template:
    src: "{{ apache_vhosts_template }}"
    dest: "{{ apache_conf_path }}/{{domain}}-{{ apache_vhosts_filename }}"
    owner: root
    group: root
    mode: 0644
  notify: restart apache
  when: apache_create_vhosts
